### ISSUE TITLE
Bluesky deployment 2022-04-19

### ISSUE THREAD

**Issue by JunAishima** [NSLS-II-XFP/profile_collection#24]
With @AbbyGi 
Bluesky workstations: xf17bm-ws1 and xf17bm-ws3
IOCs: xf17bm-ioc3 and xf17bm-disp2

**Comment by JunAishima** [comment]
acceptance test
* start up bsui
* `HTgui.show()` in bsui - lots of red Xes in the boxes, but otherwise looks ok. This is passing
* Select Excel File - /nsls2/data/xfp/legacy/data/XFP-Char/Apr2022/deploy-2022c2/acceptance-2022-2-plan.xlsx - should be 5 gray circles
* Select "Test Mode", "Check/Uncheck" twice - the gray boxes should become blue. Press Run to do the real experiment. Sample 1 selected, sample moves in video.... get a bunch of output on the bsui screen, no problems. finishes with "shutter Close ...."
* step 4 - metadata - Select Folder - use deploy folder again. Check/Uncheck to clear and Run again - note - this should have been done before step 3. once we set up a template, the "CSV file name" now becomes populated during the scans. File is test2022c2-test1.csv.csv - has uids and other information. Looks good.
* Do not change selected detector and press Align. 2 plots in one window come up. Peak fitting parameters in the window, but is junk with no beam.

**Comment by JunAishima** [comment]
xf17bm-ioc3 - softioc to softioc-xfp change
* modifying /epics/common/bl-cas/bl-cas/17bm - default.acf and eps.acf required changes to add softioc=xfp
*

**Comment by JunAishima** [comment]
TILED
* when starting up bsui on xf17bm-ws3 or BS_ENV=/nsls2/...2022-2.1-py39-tiled bsui on xf17bm-ws1, we were getting errors that looked like mongodb pointing to the wrong host. after consultation, we have an alias that is pointing to the correct host. this was put into the tiled repo holding config info, and Dan Allan pulled the changes into /nsls2/software
* now BS_ENV=/nsls2...2022-2.1-py39-tiled bsui on  xf17bm-ws1 starts up without any problems!

**Comment by JunAishima** [comment]
kafka testing
* got bsui started - but found that the xfp topic was not available - asked for the topic to be created. done
* restart bsui, run the test in the document with a consumer watching for the events, and we got everything we expected! it worked!
*

**Comment by AbbyGi** [comment]
Databroker testing

- Activated `2022-2.1-py39-tiled` environment and tested in ipython

```py
In [1]: import databroker

In [2]: databroker.__version__
Out[2]: '2.0.0b2'

In [3]: from databroker import from_profile

In [4]: c = from_profile("xfp")
WARNING:hdf5plugin:bshuf filter already loaded, skip it.
WARNING:hdf5plugin:lz4 filter already loaded, skip it.
OBJECT CACHE: Will use up to 20_222_650_982 bytes (15% of total physical RAM)
INFO:tiled.server.object_cache:Will use up to 20_222_650_982 bytes (15% of total physical RAM)

In [5]: c
Out[5]: <Catalog {1, 2, 1, 2, 3, 4, 5, 6, 7, 8, ...} ~91590 entries>

In [6]: c[-1]
Out[6]: <BlueskyRun {'primary'} scan_id=87458 uid='c4500a53' 2022-04-19 14:19>

In [7]: c[-1].primary.read()
Out[7]: 
<xarray.Dataset>
Dimensions:  (time: 1)
Coordinates:
  * time     (time) float64 1.65e+09
Data variables:
    det      (time) float64 1.0
Attributes:
    stream_name:  primary
```

**Comment by JunAishima** [comment]
Erik and I confirmed that the exception is most likely an isolated data fitting issue after repeated successful alignments, so we agreed that this bug can be fixed offline, outside of the deployment.

**Comment by JunAishima** [comment]
pulled in master, we are done!!
